const theme = {
  background: '#FFFEFC',
  blue: '#335DF8',
  mainBlue: '#2D5BFF',
  lightGray: '#F6F6F6',
  darkGray: '#DDDDDD',
  hoverGray: '#d8d8d8',
  crayonGreen: '#20DAB3',
  logoBlue: '#3b7fff',
  iconBlue: '#2180F6',
  white: '#FFFFFF',
  fontColor: '#333333',
  fontTitle: "'Alata', sans-serif;",
  fontContent: "'Noto Sans KR', sans-serif;",
  imgRadius: '4px',
  priorityStyle: {
    'border-radius': '5px',
    border: '0.5px solid #DDDDDD',
    padding: ' 10px 15px',
    'margin-right': '5px',
    'background-color': '${theme.white}',
  },
  cityStyle: {
    'margin-bottom': '16px',
    'font-size': '14px',
    opacity: '0.5',
  },
  modalStyle: {
    top: '0',
    width: '300px',
    height: '450px',
    'z-index': '5',
    'border-radius': '4px',
    border: '1px solid #DDDDDD',
    margin: '40px',
    'box-shadow': '20px',
    'align-self': 'center',
  },
  borderStyle: {
    border: '1px solid #DDDDDD',
  },
  widthHeightAuto: {
    width: 'auto',
    height: 'auto',
  },
  itemStyle: {
    display: 'inline-block',
    margin: '10px 10px',
    padding: '5px',
  },
  border1pxStyle: {
    border: '1px solid #DDDDDD',
  },
  categoryStyle: {
    'align-items': 'center',
    'text-align': 'center',
    'line-height': '35px',
    border: '0.5px solid ${theme.lightGray}',
    'border-radius': '17px',
    color: 'black',
    width: 'auto',
    height: 'auto',
    outline: 'none',
    border: 'none',
  },
};

export default theme;
